version: '3.8'
services:
 web:
  build: ./app
  image: 177547405009.dkr.ecr.eu-north-1.amazonaws.com/djengo_docker_aws2:djengo_docker_web
  command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000
  volumes:
   - ./app/:/usr/src/app/
   - static_volume:/usr/src/app/static
  expose:
   - 8000
 nginx:
  build: ./nginx
  image: 177547405009.dkr.ecr.eu-north-1.amazonaws.com/djengo_docker_aws2:djengo_docker_nginx
  volumes:
   - static_volume:/usr/src/app/static
  ports:
   - 8000:80
  depends_on:
   - web
volumes:
 static_volume:
